### ISSUE TITLE
Amazigh date correction

### ISSUE THREAD

**Issue by abdelhaqueidali** [Infrapink/calconv#8] opened 2024-12-16 01:30 UTC
14th January is the first day in the new Amazigh year, so it corresponds to 1 Yennayer. 11th being the current day is actually wrong because of many circumstances. 
If you would not like to change it, maybe creating another version that follows that, since that is how it's in Morocco and Libya Algeria got it mixed up because of many issues. From 12th being the first day, to moving it to 11th, but actually 14th is what is common in sources I have seen before. 
Tawalt :
https://tawalt.tinussan.com/%d8%a3%d9%86%d8%aa-%d9%84%d9%8a%d8%a8%d9%8a-%d8%a5%d8%b0%d8%a7-%d8%a3%d9%86%d8%aa-%d8%a3%d9%85%d8%a7%d8%b2%d9%8a%d8%ba%d9%8a/#more-843

From Wikipedia:
 "The length of the year and of the individual months is the same as in the Julian calendar: three years of 365 days followed by a leap year of 366, without exceptions, and 30- and 31-day months, except for the second one that has 28 days. The only slight discrepancy lies in that the extra day in leap years is not usually added at the end of February, but at the end of the year. This means that the beginning of the year (the first day of yennayer) corresponds to the 14th day of January in the Gregorian calendar, which coincides with the offset accumulated during the centuries between astronomical dates and the Julian calendar."
![Yennayer](https://github.com/user-attachments/assets/7a5ced78-43bd-4a8a-9d9c-b0e854930389)
"A page from a Tunisian calendar, showing the correspondence of 1 Yennayer ʿajmi (in red on bottom) with 14 January of the Gregorian calendar. The writing on the bottom signals that it is ʿajmi New Year's Day and that al-lyali al-sud ("the black nights") are beginning."

https://en.m.wikipedia.org/wiki/Berber_calendar

**Comment by Infrapink** [comment] 2024-12-16 10:23
14 January 2025 (Gregorian) → 1 Yenneyar 2975 and vice versa

1 Yenneyar 2949 → 1 January 1999 (Gregorian) and vice versa

Closing as unable to reproduce [abdelhaqueidali](https://github.com/abdelhaqueidali)'s bug

**Closed as completed by Infrapink** 2024-12-16 10:23 UTC
